export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const ADMIN_GET_ALL_ORDERS_REQUEST = "ADMIN_GET_ALL_ORDERS_REQUEST";
export const ADMIN_GET_ALL_ORDERS_SUCCESS = "ADMIN_GET_ALL_ORDERS_SUCCESS";
export const ADMIN_GET_ALL_ORDERS_FAIL = "ADMIN_GET_ALL_ORDERS_FAIL";

export const ADMIN_UPDATE_ORDER_REQUEST = "ADMIN_UPDATE_ORDER_REQUEST";
export const ADMIN_UPDATE_ORDER_SUCCESS = "ADMIN_UPDATE_ORDER_SUCCESS";
export const ADMIN_UPDATE_ORDER_FAIL = "ADMIN_UPDATE_ORDER_FAIL";
export const ADMIN_UPDATE_ORDER_RESET = "ADMIN_UPDATE_ORDER_RESET";

export const ADMIN_DELETE_ORDER_REQUEST = "ADMIN_DELETE_ORDER_REQUEST";
export const ADMIN_DELETE_ORDER_SUCCESS = "ADMIN_DELETE_ORDER_SUCCESS";
export const ADMIN_DELETE_ORDER_FAIL = "ADMIN_DELETE_ORDER_FAIL";
export const ADMIN_DELETE_ORDER_RESET = "ADMIN_DELETE_ORDER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
