export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST";
export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS";
export const ADMIN_ADD_PRODUCT_FAIL = "ADMIN_ADD_PRODUCT_FAIL";
export const ADMIN_ADD_PRODUCT_RESET = "ADMIN_ADD_PRODUCT_RESET";

export const ADMIN_GET_ALL_PRODUCTS_REQUEST = "ADMIN_GET_ALL_PRODUCT_REQUEST";
export const ADMIN_GET_ALL_PRODUCTS_SUCCESS = "ADMIN_GET_ALL_PRODUCT_SUCCESS";
export const ADMIN_GET_ALL_PRODUCTS_FAIL = "ADMIN_GET_ALL_PRODUCT_FAIL";

export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";
export const ADMIN_UPDATE_PRODUCT_RESET = "ADMIN_UPDATE_PRODUCT_RESET";

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";
export const ADMIN_DELETE_PRODUCT_RESET = "ADMIN_DELETE_PRODUCT_RESET";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
